<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AmbassadorDetails;
class AmbassadorDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     *///coin dollarvalue
    public function run()
    {
       $ambassadorDetails=[
        ['id'=>'1','user_id'=> '2', 'about'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ','city'=> 'NYC','state' =>'YC', 'relationship'=>'single','joining'=> '2020-01-28','high_school'=> 'Lorem Ipsum','workplace' =>'Lorem Ipsum', 'hobbies'=>'NYC','cover_photo'=> '1656703476vid.jpg','privacy'=> 'a:10:{s:5:\"about\";s:7:\"friends\";s:4:\"city\";s:6:\"tier-2\";s:5:\"state\";s:6:\"tier-1\";s:12:\"relationship\";s:6:\"tier-2\";s:7:\"joining\";s:6:\"public\";s:11:\"high_school\";s:6:\"public\";s:9:\"workplace\";s:7:\"friends\";s:7:\"hobbies\";s:6:\"tier-1\";s:5:\"phone\";s:7:\"friends\";s:6:\"gender\";s:6:\"tier-1\";}', 'network_privacy'=>'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'2','user_id'=>'3', 'about'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ', 'city'=>'NYC', 'state' =>'YC','relationship'=> 'single','joining'=> '2020-01-28', 'high_school'=> 'Lorem Ipsum', 'workplace' =>'Lorem Ipsum', 'hobbies'=>'Lorem Ipsum','cover_photo'=> NULL, 'privacy'=> NULL,  'network_privacy'=>'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'3','user_id'=> '4','about'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ','city'=> 'NYC','state' => 'YC','relationship'=> 'single', 'joining'=>'2020-01-28', 'high_school'=> 'Lorem Ipsum','workplace' => 'Lorem Ipsum','hobbies'=> 'Lorem Ipsum','cover_photo'=> NULL,'privacy'=>  NULL, 'network_privacy'=> 'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'4','user_id'=>'5', 'about'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ', 'city'=>'NYC', 'state' =>'YC', 'relationship'=>'single', 'joining'=>'2020-01-28', 'high_school'=> 'Lorem Ipsum', 'workplace' =>'Lorem Ipsum', 'hobbies'=>'Lorem Ipsum', 'cover_photo'=>NULL, 'privacy'=> NULL, 'network_privacy'=> 'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'5','user_id'=> '6','about'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ','city'=> 'NYC','state' => 'YC','relationship'=> 'single','joining'=> '2020-01-28','high_school'=>  'Lorem Ipsum', 'workplace' =>'Lorem Ipsum', 'hobbies'=>'Lorem Ipsum','cover_photo'=> NULL,'privacy'=>  NULL, 'network_privacy'=> 'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'6','user_id'=> '7','about'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ', 'city'=>'NYC', 'state' =>'YC','relationship'=> 'single', 'joining'=>'2020-01-28', 'high_school'=> 'Lorem Ipsum', 'workplace' =>'Lorem Ipsum', 'hobbies'=>'Lorem Ipsum','cover_photo'=> NULL,'privacy'=>  NULL,  'network_privacy'=>'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'7','user_id'=> '8', 'about'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ', 'city'=>'NYC', 'state' =>'YC', 'relationship'=>'single', 'joining'=>'2020-01-28', 'high_school'=> 'Lorem Ipsum', 'workplace' =>'Lorem Ipsum','hobbies'=> 'Lorem Ipsum', 'cover_photo'=>NULL, 'privacy'=> NULL,  'network_privacy'=>'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'8','user_id'=> '9','about'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ', 'city'=>'NYC', 'state' =>'YC', 'relationship'=>'single','joining'=> '2020-01-28', 'high_school'=> 'Lorem Ipsum', 'workplace' =>'Lorem Ipsum', 'hobbies'=>'Lorem Ipsum','cover_photo'=> NULL, 'privacy'=> NULL,  'network_privacy'=>'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'9','user_id'=> '10', 'about'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ','city'=> 'NYC', 'state' =>'YC','relationship'=> 'single','joining'=> '2020-01-28', 'high_school'=> 'Lorem Ipsum','workplace' => 'Lorem Ipsum','hobbies'=> 'Lorem Ipsum','cover_photo'=> NULL, 'privacy'=> NULL, 'network_privacy'=> 'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'10','user_id'=> '11', 'about'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ','city'=> 'NYC', 'state' =>'YC','relationship'=> 'single', 'joining'=>'2020-01-28','high_school'=>  'Lorem Ipsum','workplace' => 'Lorem Ipsum','hobbies'=> 'Lorem Ipsum','cover_photo'=> NULL,'privacy'=>  NULL, 'network_privacy'=> 'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'11','user_id'=>'12', 'about'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ','city'=> 'NYC', 'state' =>'YC', 'relationship'=>'single','joining'=> '2020-01-28', 'high_school'=> 'Lorem Ipsum', 'workplace' =>'Lorem Ipsum', 'hobbies'=>'Lorem Ipsum', 'cover_photo'=>NULL, 'privacy'=> NULL,  'network_privacy'=>'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'12','user_id'=>'13', 'about'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ', 'city'=>'NYC', 'state' =>'YC', 'relationship'=>'single', 'joining'=>'2020-01-28', 'high_school'=> 'Lorem Ipsum', 'workplace' =>'Lorem Ipsum', 'hobbies'=>'Lorem Ipsum', 'cover_photo'=>NULL, 'privacy'=> NULL,  'network_privacy'=>'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}'],
        ['id'=>'13','user_id'=> '14','about'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id libero sit orci sed vel rutrum aliquam. ','city'=> 'NYC','state' => 'YC','relationship'=> 'single','joining'=> '2020-01-28', 'high_school'=> 'Lorem Ipsum', 'workplace' =>'Lorem Ipsum','hobbies'=> 'Lorem Ipsum','cover_photo'=> NULL,'privacy'=>  NULL,  'network_privacy'=>'a:2:{s:7:\"friends\";s:7:\"friends\";s:11:\"connections\";s:7:\"friends\";}']
       ];
       foreach($ambassadorDetails as $item)
       {
        AmbassadorDetails::create($item);
       }
    }
}
